# Site settings
title: clml.tutorials 
email: mike.maul@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tutorials for CLML the Common Lisp Machine Learning package.
baseurl: "/clml.tutorials/" # the subpath of your site, e.g. /blog/
url: "https://mmaul.github.io/clml.tutorials/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: mmaul 

# Build settings
markdown: kramdown
